''                    Vendor             ;Vendor PN              ;Shape                        ;Notes
'22pF/50V'            MURATA             ;GRM1555C1H220J         ;C0402                        ;
'33pF/50V'            TDK                ;C1005C0G1H330G050BA    ;C0402                        ;
'220pF/50V'           TDK                ;C1005C0G1H221J050BA    ;C0402                        ;
'820pF/50V'           TDK                ;C1005C0G1H821J050BA    ;C0402                        ;
'2200pF/16V'          MURATA             ;GRM033R71C222K         ;C0201                        ;
'0.01uF/16V'          MURATA             ;GRM155R71C103K         ;C0402                        ;
'0.1uF/6.3V'          MURATA             ;GRM155R710J104K        ;C0402                        ;
'0.1uF/16V'           MURATA             ;GRM155R71C104K         ;C0402                        ;
'0.1uF/50V'           TDK                ;C1005X7R1H104K050BB    ;C0402                        ;
'0.033uF/50V'         MURATA             ;GRM188R71H333J         ;C0603                        ;
'1.0uF/16V'           MURATA             ;GRM21BR71C105K         ;C0805                        ;X7R
'4.7uF/10V'           TDK                ;C2012X7R1A475M125AC    ;C0805                        ;
'10uF/4V'             MURATA             ;GRM155R60G106M         ;C0402                        ;X5R
'10uF/16V'            TDK                ;CGA5L1X7R1C106K        ;C1206                        ;
'10uF/35V'            TDK                ;CGA5L1X7R1V106K160AC   ;C1206                        ;
'470uF/16V'           PANASONIC          ;16SEPC470M             ;RC197\425+                   ;
'1000uF/16V'          PANASONIC          ;16SEPF1000M            ;RC197\425+                   ;ALT. Nippon Chemicon APSG160ELL102MH20S
'C4A-0.1uF'           AVX                ;W2A4ZC104MAT2A         ;ARRAY_W2A4                   ;
'0 OHM'               VISHAY             ;CRCW04020000Z0ED       ;R0402                        ;
'2.2 OHM'             VISHAY             ;CRCW04022R20JN         ;R0402                        ;
'5.1 OHM'             VISHAY             ;CRCW20105R10JN         ;2010                         ;
'10 OHM'              VISHAY             ;CRCW040210R0JN         ;R0402                        ;
'33 OHM'              VISHAY             ;CRCW020133R0JN         ;R0201                        ;
'220 OHM'             VISHAY             ;CRCW0402220RJN         ;R0402                        ;
'330 OHM'             VISHAY             ;CRCW0402330RJN         ;R0402                        ;
'100 OHM'             VISHAY             ;CRCW0201330RJN         ;R0201                        ;SMALL IN THE ARRAY
'1K'                  VISHAY             ;CRCW04021K00JN         ;R0402                        ;
'1.2K'                VISHAY             ;CRCW04021K20JN         ;R0201                        ;SMALL IN THE ARRAY
'4.7K'                VISHAY             ;CRCW04024K70JN         ;R0402                        ;
'10K'                 VISHAY             ;CRCW020110K0JN         ;R0201                        ;SMALL IN THE ARRAY
'20K'                 VISHAY             ;CRCW020120K0JN         ;R0201                        ;SMALL IN THE ARRAY
'100K'                VISHAY             ;CRCW0201100KJN         ;R0201                        ;SMALL IN THE ARRAY
'3.65K 1%'            VISHAY             ;CRCW04023K65FK         ;R0402                        ;
'3.90K 1%'            VISHAY             ;CRCW04023K90FK         ;R0402                        ;
'11.0K 1%'            VISHAY             ;CRCW040211K0FK         ;R0402                        ;
'20.0K 1%'            VISHAY             ;CRCW040220K0FK         ;R0402                        ;
'30.0K 1%'            VISHAY             ;CRCW040230K0FK         ;R0402                        ;
'43.2K 1%'            VISHAY             ;CRCW040243K2FK         ;R0402                        ;
'49.9K 1%'            VISHAY             ;CRCW040249K9FK         ;R0402                        ;
'60.4K 1%'            VISHAY             ;CRCW040260K4FK         ;R0402                        ;
'80.6K 1%'            VISHAY             ;CRCW040280K6FK         ;R0402                        ;
'100K 1%'             VISHAY             ;CRCW0402100KFK         ;R0402                        ;
'499K 1%'             VISHAY             ;CRCW0402499KFK         ;R0402                        ;
'10.0M'               VISHAY             ;CRCW040210M0JN         ;R0402                        ;
'100KT'               MURATA             ;NCU18WF104F60RB        ;R0603                        ;THERMISTOR
'R4A-33 OHM'          VISHAY             ;CRA06S083033RJ         ;ARRAY_CRA06S0831             ;
'R4A-100 OHM'         VISHAY             ;CRA06S083101RJ         ;ARRAY_CRA06S0831             ;
'R4A-10K'             VISHAY             ;CRA06S083103RJ         ;ARRAY_CRA06S0831             ;
'R4A-1M'              VISHAY             ;CRA06S0831M00J         ;ARRAY_CRA06S0831             ;
'8.00MHZ'             CARDINAL COMP      ;CX532Z-A2B3C5-70-8.0D18;CRY_CX532                    ;
'0.40uH'              COILCRAFT          ;XAL1060-401MEB         ;IND_XAL1060-401              ;
'1.2uH'               COILCRAFT          ;XAL1060-122MEB         ;IND_XAL1060-401/1350         ;
'TMP37GRTZ'           ANALOG DEVICES     ;TMP37GRTZ-REEL7        ;SOT-23-5                     ;
'AD5111BCPZ80'        ANALOG DEVICES     ;AD5111BCPZ80           ;LFCSP8_UD_2X2MM              ;
'BLAKE2B'             CSS                ;BLAKE2B                ;BGA144_.8MM_10X10MM          ;
'BAT54S'              DIODES INC         ;BAT54S-7-F             ;SOT-23                       ;
'DFLS1100-7'          DIODES INC         ;DFLS1100-7             ;POWERDI_123                  ;
'BSC015NE2LS5I'       INFINEON           ;BSC015NE2LS5I          ;POWERPAK-SO8                 ;
'BSC018NE2LS'         INFINEON           ;BSC018NE2LSIATMA1      ;POWERPAK-SO8                 ;
'LTC3855IFE#PBF'      LINEAR TECH        ;LTC3855IFE#PBF         ;DIP38_SSOP_TP                ;
'FUSE-5A'             LITTELFUSE         ;0451005.MRL            ;FUSE\LF-0451                 ;
'MINIFIT_JR_6P'       MOLEX              ;0039301061             ;MOLEX\39-30-0060             ;
'BEAD1'               MURATA             ;BLM21PG300SN1D         ;0805                         ;
'IP4220CZ6'           NEXPERIA           ;IP4220CZ6              ;TSOP-6                       ;
'MUN5235DW1'          ON SEMI            ;MUN5235DW1T1G          ;SOT-363                      ;
'MUN5335DW1'          ON SEMI            ;MUN5335DW1T1G          ;SOT-363                      ;
'MUN2235T1G'          ON SEMI            ;MMUN2235LT1G           ;SOT-23                       ;
'MMBD4148'            ON SEMI            ;MMBD4148SE             ;SOT-23                       ;
'CON2'                SAMTEC             ;TSW-102-23-T-S         ;SIP\2P                       ;
'CONN_COMM'           SAMTEC             ;TSW-105-23-T-S         ;SIP\5P                       ;
'HEADER 5X2'          SAMTEC             ;TSW-105-23-T-D         ;J\10P                        ;
'HEADER 10X2'         SAMTEC             ;TSW-110-23-T-D         ;J\20P                        ;
'HEADER 10X2S'        3M                 ;D2520-6002             ;3M_D2520-6002                ;
'STM32F101V8'         ST MICRO           ;STM32F101V8T6TR        ;LQFP100_14X14MM              ;
'BAT30F4'             ST MICRO           ;BAT30F4                ;DIODE_BAT30F4                ;
'SN74LVC541ADW'       TI                 ;SN74LVC541ADWR         ;DIP20_SOL                    ;
'SN74AVC4T245DR'      TI                 ;SN74AVC4T245DR         ;DIP16_SO                     ;
'SN74LVC2G14DB'       TI                 ;SN74LVC2G14DBVRE4      ;SOT-23-6                     ;
'CD4097BPWR'          TI                 ;CD4097BPWR             ;DIP24\TSSOP                  ;
'TLV272CDR'           TI                 ;TLV272CDR              ;DIP8\SO                      ;
'SN74AVC8T245PW'      TI                 ;SN74AVC8T245PW         ;DIP24\TSSOP                  ;
'TPS70912DRVR'        TI                 ;TPS70912DRVR           ;DIP6_WSON_TP                 ;
'TPS70933DRVR'        TI                 ;TPS70933DRVR           ;DIP6_WSON_TP                 ;
'SN74LVC1G3157DBV'    TI                 ;SN74LVC13157DBVR       ;SOT-23-6                     ;
'TLMG1100'            VISHAY             ;TLMG1100-GS08          ;LED\0603                     ;
'VBUS054B-HSF'        VISHAY             ;VBUS054B-HSF           ;ARRAY_VBUS054B-HSF           ;
'BJC'                 OTEC JUMPER        ;DO NOT POPULATE        ;OTEC_BJC                     ;BOARD SHAPE - CLOSED
'BJO'                 OTEC JUMPER        ;DO NOT POPULATE        ;OTEC_BJO                     ;BOARD SHAPE - OPEN
'TP'                  OTEC TEST POINT    ;DO NOT POPULATE        ;TPTOP                        ;
'HOLE125-250'         OTEC MOUNTING HOLE ;DO NOT POPULATE        ;HOLE125-250                  ;
'MTGHOLE'             MOUNTING HOLE      ;DO NOT POPULATE        ;HOLE171-350                  ;
'DNP-0201'            --                 ;DO NOT POPULATE        ;R0201                        ;
'DNP'                 --                 ;DO NOT POPULATE        ;R0402                        ;
'DNP-C0402'           --                 ;DO NOT POPULATE        ;C0402                        ;
'DNP-1206'            --                 ;DO NOT POPULATE        ;1206                         ;
'DNP-2010'            --                 ;DO NOT POPULATE        ;2010                         ;
'DNP-MOSFETN'         --                 ;DO NOT POPULATE        ;POWERPAK-SO8                 ;
